spring:
  application:
    name: wordwise
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

rapid:
  client:
    key: ${RAPID_API_KEY}

naver:
  client:
    id: ${NAVER_API_ID}
    key: ${NAVER_API_KEY}

logging:
  level:
    com.devloop.search.service: DEBUG

